/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AAssnExpr extends PExpr
{
    private PAssignExpr _assignExpr_;

    public AAssnExpr()
    {
        // Constructor
    }

    public AAssnExpr(
        @SuppressWarnings("hiding") PAssignExpr _assignExpr_)
    {
        // Constructor
        setAssignExpr(_assignExpr_);

    }

    @Override
    public Object clone()
    {
        return new AAssnExpr(
            cloneNode(this._assignExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssnExpr(this);
    }

    public PAssignExpr getAssignExpr()
    {
        return this._assignExpr_;
    }

    public void setAssignExpr(PAssignExpr node)
    {
        if(this._assignExpr_ != null)
        {
            this._assignExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignExpr_ == child)
        {
            this._assignExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignExpr_ == oldChild)
        {
            setAssignExpr((PAssignExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
