/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStmt extends PAssignStmt
{
    private PAssignExpr _assignExpr_;
    private TSemi _semi_;

    public AAssignStmt()
    {
        // Constructor
    }

    public AAssignStmt(
        @SuppressWarnings("hiding") PAssignExpr _assignExpr_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setAssignExpr(_assignExpr_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStmt(
            cloneNode(this._assignExpr_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStmt(this);
    }

    public PAssignExpr getAssignExpr()
    {
        return this._assignExpr_;
    }

    public void setAssignExpr(PAssignExpr node)
    {
        if(this._assignExpr_ != null)
        {
            this._assignExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignExpr_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignExpr_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignExpr_ == child)
        {
            this._assignExpr_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignExpr_ == oldChild)
        {
            setAssignExpr((PAssignExpr) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
