/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AForNoShortStmtNoShortIf extends PStmtNoShortIf
{
    private PForStmtNoShortIf _forStmtNoShortIf_;

    public AForNoShortStmtNoShortIf()
    {
        // Constructor
    }

    public AForNoShortStmtNoShortIf(
        @SuppressWarnings("hiding") PForStmtNoShortIf _forStmtNoShortIf_)
    {
        // Constructor
        setForStmtNoShortIf(_forStmtNoShortIf_);

    }

    @Override
    public Object clone()
    {
        return new AForNoShortStmtNoShortIf(
            cloneNode(this._forStmtNoShortIf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForNoShortStmtNoShortIf(this);
    }

    public PForStmtNoShortIf getForStmtNoShortIf()
    {
        return this._forStmtNoShortIf_;
    }

    public void setForStmtNoShortIf(PForStmtNoShortIf node)
    {
        if(this._forStmtNoShortIf_ != null)
        {
            this._forStmtNoShortIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forStmtNoShortIf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forStmtNoShortIf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forStmtNoShortIf_ == child)
        {
            this._forStmtNoShortIf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forStmtNoShortIf_ == oldChild)
        {
            setForStmtNoShortIf((PForStmtNoShortIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
