/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseStStmt extends PStmt
{
    private PIfElseStmt _ifElseStmt_;

    public AIfElseStStmt()
    {
        // Constructor
    }

    public AIfElseStStmt(
        @SuppressWarnings("hiding") PIfElseStmt _ifElseStmt_)
    {
        // Constructor
        setIfElseStmt(_ifElseStmt_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseStStmt(
            cloneNode(this._ifElseStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseStStmt(this);
    }

    public PIfElseStmt getIfElseStmt()
    {
        return this._ifElseStmt_;
    }

    public void setIfElseStmt(PIfElseStmt node)
    {
        if(this._ifElseStmt_ != null)
        {
            this._ifElseStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifElseStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifElseStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifElseStmt_ == child)
        {
            this._ifElseStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifElseStmt_ == oldChild)
        {
            setIfElseStmt((PIfElseStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
