/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AMultassnExpr extends PExpr
{
    private PMultassignExpr _multassignExpr_;

    public AMultassnExpr()
    {
        // Constructor
    }

    public AMultassnExpr(
        @SuppressWarnings("hiding") PMultassignExpr _multassignExpr_)
    {
        // Constructor
        setMultassignExpr(_multassignExpr_);

    }

    @Override
    public Object clone()
    {
        return new AMultassnExpr(
            cloneNode(this._multassignExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultassnExpr(this);
    }

    public PMultassignExpr getMultassignExpr()
    {
        return this._multassignExpr_;
    }

    public void setMultassignExpr(PMultassignExpr node)
    {
        if(this._multassignExpr_ != null)
        {
            this._multassignExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multassignExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multassignExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multassignExpr_ == child)
        {
            this._multassignExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multassignExpr_ == oldChild)
        {
            setMultassignExpr((PMultassignExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
