/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AMultassignStmt extends PMultassignStmt
{
    private PMultassignExpr _multassignExpr_;
    private TSemi _semi_;

    public AMultassignStmt()
    {
        // Constructor
    }

    public AMultassignStmt(
        @SuppressWarnings("hiding") PMultassignExpr _multassignExpr_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setMultassignExpr(_multassignExpr_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AMultassignStmt(
            cloneNode(this._multassignExpr_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultassignStmt(this);
    }

    public PMultassignExpr getMultassignExpr()
    {
        return this._multassignExpr_;
    }

    public void setMultassignExpr(PMultassignExpr node)
    {
        if(this._multassignExpr_ != null)
        {
            this._multassignExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multassignExpr_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multassignExpr_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multassignExpr_ == child)
        {
            this._multassignExpr_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multassignExpr_ == oldChild)
        {
            setMultassignExpr((PMultassignExpr) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
