/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class ARvalExpr extends PExpr
{
    private PRvalue _rvalue_;

    public ARvalExpr()
    {
        // Constructor
    }

    public ARvalExpr(
        @SuppressWarnings("hiding") PRvalue _rvalue_)
    {
        // Constructor
        setRvalue(_rvalue_);

    }

    @Override
    public Object clone()
    {
        return new ARvalExpr(
            cloneNode(this._rvalue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARvalExpr(this);
    }

    public PRvalue getRvalue()
    {
        return this._rvalue_;
    }

    public void setRvalue(PRvalue node)
    {
        if(this._rvalue_ != null)
        {
            this._rvalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rvalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rvalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rvalue_ == child)
        {
            this._rvalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rvalue_ == oldChild)
        {
            setRvalue((PRvalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
