/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AStmtNoTrlrStmt extends PStmt
{
    private PStmtNoTrailer _stmtNoTrailer_;

    public AStmtNoTrlrStmt()
    {
        // Constructor
    }

    public AStmtNoTrlrStmt(
        @SuppressWarnings("hiding") PStmtNoTrailer _stmtNoTrailer_)
    {
        // Constructor
        setStmtNoTrailer(_stmtNoTrailer_);

    }

    @Override
    public Object clone()
    {
        return new AStmtNoTrlrStmt(
            cloneNode(this._stmtNoTrailer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtNoTrlrStmt(this);
    }

    public PStmtNoTrailer getStmtNoTrailer()
    {
        return this._stmtNoTrailer_;
    }

    public void setStmtNoTrailer(PStmtNoTrailer node)
    {
        if(this._stmtNoTrailer_ != null)
        {
            this._stmtNoTrailer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtNoTrailer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stmtNoTrailer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stmtNoTrailer_ == child)
        {
            this._stmtNoTrailer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stmtNoTrailer_ == oldChild)
        {
            setStmtNoTrailer((PStmtNoTrailer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
