/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AUntilStStmt extends PStmt
{
    private PUntilStmt _untilStmt_;

    public AUntilStStmt()
    {
        // Constructor
    }

    public AUntilStStmt(
        @SuppressWarnings("hiding") PUntilStmt _untilStmt_)
    {
        // Constructor
        setUntilStmt(_untilStmt_);

    }

    @Override
    public Object clone()
    {
        return new AUntilStStmt(
            cloneNode(this._untilStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUntilStStmt(this);
    }

    public PUntilStmt getUntilStmt()
    {
        return this._untilStmt_;
    }

    public void setUntilStmt(PUntilStmt node)
    {
        if(this._untilStmt_ != null)
        {
            this._untilStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._untilStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._untilStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._untilStmt_ == child)
        {
            this._untilStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._untilStmt_ == oldChild)
        {
            setUntilStmt((PUntilStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
