/* This file was generated by SableCC (http://www.sablecc.org/). */

package decaf.node;

import decaf.analysis.*;

@SuppressWarnings("nls")
public final class AWhileNoShortStmtNoShortIf extends PStmtNoShortIf
{
    private PWhileStmtNoShortIf _whileStmtNoShortIf_;

    public AWhileNoShortStmtNoShortIf()
    {
        // Constructor
    }

    public AWhileNoShortStmtNoShortIf(
        @SuppressWarnings("hiding") PWhileStmtNoShortIf _whileStmtNoShortIf_)
    {
        // Constructor
        setWhileStmtNoShortIf(_whileStmtNoShortIf_);

    }

    @Override
    public Object clone()
    {
        return new AWhileNoShortStmtNoShortIf(
            cloneNode(this._whileStmtNoShortIf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileNoShortStmtNoShortIf(this);
    }

    public PWhileStmtNoShortIf getWhileStmtNoShortIf()
    {
        return this._whileStmtNoShortIf_;
    }

    public void setWhileStmtNoShortIf(PWhileStmtNoShortIf node)
    {
        if(this._whileStmtNoShortIf_ != null)
        {
            this._whileStmtNoShortIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileStmtNoShortIf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileStmtNoShortIf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileStmtNoShortIf_ == child)
        {
            this._whileStmtNoShortIf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileStmtNoShortIf_ == oldChild)
        {
            setWhileStmtNoShortIf((PWhileStmtNoShortIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
